# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]

# - repo: https://github.com/streetsidesoftware/cspell-cli
#   rev: v6.31.0
#   hooks:
#   - id: cspell

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    require_serial: true
    types_or: [python, pyi]

  - id: mypy
    name: mypy
    entry: mypy
    language: system
    require_serial: true
    types_or: [python, pyi]

  - id: ruff
    name: ruff
    entry: ruff
    language: system
    require_serial: true
    types_or: [python, pyi]
