[tool.poetry]
name = "business-card"
version = "0.1.0"
description = ""
authors = ["scary <scary@scary.com>"]
readme = "README.md"
packages = [{include = "business_card"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^2.25.1"
loguru = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
